name: Bug report
description: Report a bug you found in this project
title: "[Bug]"
labels: ["bug"]
assignees:
  - JackA1ltman

body:
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the bug.

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened?

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any screenshots, log files, or extra context about the problem here.
