name: Device Request
description: Request a kernel port for a specific device and ROM
title: "[DevicePort]"
labels: ["help wanted"]
assignees:
  - JackA1ltman

Body:
  - type: input
    attributes:
      label: Device Name
      description: ex. OnePlus8
    validations:
      required: true

  - type: input
    attributes:
      label: Device Codename
      description: ex. instantnoodle
    validations:
      required: true

  - type: input
    attributes:
      label: ROM Name
      description: ex. OxygenOS
    validations:
      required: true

  - type: input
    attributes:
      label: ROM Version
      description: ex. 13.1
    validations:
      required: true

  - type: input
    attributes:
      label: Android Version
      description: ex. 13
    validations:
      required: true

  - type: input
    attributes:
      label: Kernel Source Link
      description: ex. https://github.com/oppo-source/android_kernel_oppo_sm8250

  - type: input
    attributes:
      label: Kernel Source Branch
      description: ex. oppo/sm8250_s_12.1

  - type: input
    attributes:
      label: Kernel Version
      description: ex. 4.19.325
