name: 'Patch ReKernel for Kernel.'

runs:
  using: 'composite'
  steps:
      - name: Patch ReKernel
        if: env.REKERNEL_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/
          cp /tmp/Patches/Rekernel/rekernel_patches.sh ./
          bash rekernel_patches.sh

          git clone https://github.com/Sakion-Team/Re-Kernel.git -b main ReKernel
          mv ReKernel/Integrate/rekernel drivers/

          echo "CONFIG_REKERNEL=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_REKERNEL_NETWORK=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}

          echo "Patched Re:Kernel for your kernel successfully."
