name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
 
  ## Redmi
  build-pocof1-aosp-a16:
    name: "Poco F1 (Based-AOSP A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-pocof1-aosp-a16.yml
    secrets: inherit
