name: Build Onelus 8 Series (OxygenOS 13 A13) (XTD Kernel)

on:
  workflow_call:

env:
  # Device env
  DEVICE_NAME : "oneplus_8_cn"
  DEVICE_CODENAME : "instantnoodle"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld"

  KERNEL_SOURCE : "https://github.com/ppajda/android_kernel_oneplus_sm8250.git"
  KERNEL_BRANCH : "oos13.1"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://github.com/JackA1ltman/Google-GCC-Android-4.9.git"
  GCC_64_BRANCH : "aarch64"
  GCC_32_SOURCE : "https://github.com/JackA1ltman/Google-GCC-Android-4.9.git"
  GCC_32_BRANCH : "arm32"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "xtd_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : "https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/12107%2B155/kernel/setup.sh"
  KERNELSU_BRANCH : "12107+155"
  KERNELSU_NAME : "KernelSU"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true
  SUSFS_UPDATE : false

  AK3_SOURCE : "https://github.com/JackA1ltman/OP8_AnyKernel3.git"
  AK3_BRANCH : "main"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "oxygen13.1_a13"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.

  KERNELSU_METHOD: "shell" # shell, manual and only.
  KERNELSU_SUS_PATCH: "false" # if u need manual susfs patch to kernelsu.

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "op_kernel" # [your_branch] -> main

  HOOK_METHOD: "normal" # manual hook method,can choice syscall and normal.
  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.

  KPM_ENABLE: "false" # Only use it for SukiSU-Ultra.
  KPM_FIX: "false" # Fix Error When Enabling KPM.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "false" # Merge config files.

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

  REKERNEL_ENABLE: "false" # if u need Re:Kernel.

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Execuate common process
        uses: ./.github/workflows/install-env

      - name: ⚙️ Compilation preparation
        uses: ./.github/workflows/build-ready

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel
          echo "CONFIG_CPU_BIG_ENDIAN=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_LTO_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_INIT_STACK_NONE=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_KPROBES=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          sed -i 's/# CONFIG_SECCOMP is not set/CONFIG_SECCOMP=y/' ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}

          # sed -i 's|\$(obj)/config_data.gz: [^ ]* FORCE|\$(obj)/config_data.gz: $(KCONFIG_CONFIG) FORCE|' kernel/Makefile

      - name: Patch Kernel of SUSFS
        if: env.SUSFS_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/
          cp susfs4ksu/kernel_patches/50_add_susfs_in_kernel-${{ env.KERNEL_VERSION }}.patch ./

          patch -p1 < 50_add_susfs_in_kernel-${{ env.KERNEL_VERSION }}.patch || true

          # Fixed Kernel Patch
          cp NonGKI_Kernel_Patches/kona_oos/namespace_fixed.patch ./
          cp NonGKI_Kernel_Patches/kona_oos/task_mmu_fixed.patch ./

          patch -p1 < namespace_fixed.patch || true
          patch -p1 < task_mmu_fixed.patch || true

      - name: Updated SUSFS Version
        if: env.SUSFS_ENABLE == 'true' && env.SUSFS_UPDATE == 'true'
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/

          # Upgrade 1.5.7
          cp /tmp/Patches/Patch/susfs_upgrade_to_157.patch ./

          patch -p1 < susfs_upgrade_to_157.patch || true

          # Upgrade 1.5.8
          if grep -q "CONFIG_KSU" "fs/exec.c"; then
            cp /tmp/Patches/Patch/susfs_upgrade_to_158_${{ env.KERNEL_VERSION }}.patch ./
            patch -p1 < susfs_upgrade_to_158_${{ env.KERNEL_VERSION }}.patch || true
            echo "Detected no-kprobe hook, use no-kprobe patch."
          elif [[ "${{ env.KERNEL_VERSION }}" == "5.4" ]]; then
            cp /tmp/Patches/Patch/susfs_upgrade_to_158_5.4_kprobe.patch ./
            patch -p1 < susfs_upgrade_to_158_5.4_kprobe.patch || true
            echo "Cannot detected no-kprobe hook in kernel 5.4, use kprobe patch."
          else
            echo "kernel version<5.4 cannot use kprobe patch."
          fi
          ## Fixed ZYGOTE_ISO error
          sed -i '/#define CMD_SUSFS_HIDE_SUS_MNTS_FOR_ALL_PROCS 0x55561/a \#define CMD_SUSFS_UMOUNT_FOR_ZYGOTE_ISO_SERVICE 0x55562' include/linux/susfs_def.h

          # Upgrade 1.5.9
          cp /tmp/Patches/Patch/susfs_upgrade_to_159.patch ./

          patch -p1 < susfs_upgrade_to_159.patch || true

          # Upgrade 1.5.10
          if grep -q "CONFIG_KSU" "fs/exec.c"; then
            cp /tmp/Patches/Patch/susfs_upgrade_to_1510_${{ env.KERNEL_VERSION }}.patch ./
            patch -p1 < susfs_upgrade_to_1510_${{ env.KERNEL_VERSION }}.patch || true
            echo "Detected no-kprobe hook, use no-kprobe patch to update 1.5.10."
          elif [[ "${{ env.KERNEL_VERSION }}" == "5.4" ]]; then
            cp /tmp/Patches/Patch/susfs_upgrade_to_1510_5.4_kprobe.patch ./
            patch -p1 < susfs_upgrade_to_1510_5.4_kprobe.patch || true
            echo "Cannot detected no-kprobe hook in kernel 5.4, use kprobe patch to update 1.5.10."
          else
            echo "kernel version<5.4 cannot use kprobe patch to update 1.5.10."
          fi

          # Extra SUSFS Patch
          # cp NonGKI_Kernel_Patches/[patch_folder]/[patch_file].patch ./

          # patch -p1 < [patch_file].patch || true

      - name: Patch Kernel of Re:Kernel
        if: env.REKERNEL_ENABLE == 'true'
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/
          PATCH_FILE="/tmp/Patches/Rekernel/rekernel-${{ env.KERNEL_VERSION }}.patch"

          if [ -f "$PATCH_FILE" ]; then
            cp /tmp/Patches/Rekernel/rekernel-${{ env.KERNEL_VERSION }}.patch ./
            patch -p1 < rekernel-${{ env.KERNEL_VERSION }}.patch || true
            echo "Re:Kernel Patched."
          else
            echo "Your kernel not supported it."
          fi

          # Extra ReKernel Patch
          # cp NonGKI_Kernel_Patches/[patch_folder]/[patch_file].patch ./

          # patch -p1 < [patch_file].patch || true

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
