name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  ## Poco
  build-poco-f1-aosp-a16:
    name: "Poco F1 (Based-AOSP A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-poco-f1-aosp-a16.yml
    secrets: inherit

 
