name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  build-oneplus-8-series-oos13-a13-xtd:
    strategy:
      fail-fast: true
    uses: ./.github/workflows/devices/build-oneplus-8-series-oos13-a13-xtd.yml
    secrets: inherit
